meta_name: "City explorer"
meta_title: "City explorer - Your local urban adventures "
meta_description: "City explorer is the best way to discover your city in a fun way"
meta_image: "logo.png" # should exist in `app/assets/images/`
